# Generated by Django 4.0.3 on 2022-03-29 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_price_books_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
