# Generated by Django 4.0.3 on 2022-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_books_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='created_date',
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
